[package]
name = "crux_language_support_zed"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/crux.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.7.0"
