[package]
name = "crux language support"
version = "0.0.1"
description = "Crux language support for Zed"
authors = ["Theophilus Nenhanga"]
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
